app = "ecommerce-support-bot"
primary_region = "ord"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8000"
  ENVIRONMENT = "production"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 2

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[http_service.concurrency]
  type = "requests"
  hard_limit = 25
  soft_limit = 20

[[mounts]]
  source = "uploads"
  destination = "/app/uploads"
  initial_size = "1gb"

[deploy]
  release_command = "alembic upgrade head"

[checks]
  [checks.health]
    type = "http"
    path = "/health"
    interval = "30s"
    timeout = "10s"
    grace_period = "5s"

[metrics]
  port = 9091
  path = "/metrics"